#!/bin/bash

# Prompt the user for their password using a graphical popup
password=$(zenity --password --title="Update Application" --timeout=10)

# Check if the password was entered successfully
if [[ $? -eq 0 ]]; then
    # Run the script with sudo permissions
    echo "$password" | sudo -S curl -LJ -o /bin/quatro-tetris \
    https://raw.githubusercontent.com/zcraftelite9495/codingstuffs/main/Python/Personal%20Project%202024/Quatro-Tetris/quatro-tetris
    
    # Download the codingstuffs repository
    git clone https://github.com/zcraftelite9495/codingstuffs.git

    # Copy the Quatro-Tetris folder to the desired destination
    cp -R codingstuffs/Python/Personal\ Project\ 2024/Quatro-Tetris/* /Games/Quatro\ Tetris

    # Clean up temporary files
    rm -rf codingstuffs

    echo "Update installed successfully!"
else
    echo "Password entry canceled, update aborted."
fi